server:
  port: 8099
spring:
  redis:
    host: 127.0.0.100
    port: 6379
    timeout: 10000
    password: password
    database: 0
    lettuce:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: 1000
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 500
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 300


