spring:
  # rabbitmq配置信息 RabbitProperties类
  rabbitmq:
    host: 47.93.149.147
    port: 5672
    username: admin
    password: 032727_wang
    virtual-host: /
    # 开启confirm机制 将其设置为 "correlated" 表示开启了发布者确认机制，用于确保消息是否成功发送到 RabbitMQ 服务器。
    publisher-confirm-type: correlated
    # 开启return机制 将其设置为 "true" 表示开启了发布者返回机制，用于处理发送到不存在的交换机或无法路由的消息。
    publisher-returns: true
    #全局配置，局部配置存在就以局部为准
    listener:
      simple:
        acknowledge-mode: manual # 手动ACK
server:
  port: 8099