alipay:
  appId: xxx
  appPrivateKey: key
  alipayPublicKey: key
  notifyUrl: http://3af06a3.r26.cpolar.top/notify
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  return-url: http://3af06a3.r26.cpolar.top/alipay.html
server:
  port: 8848
